apiVersion: v1
kind: Service
metadata:
  name: collector
spec:
  selector:
    app: collector
  ports:
  - port: ${COLLECTOR_PORT}
    targetPort: ${COLLECTOR_PORT}
---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: collector
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: collector
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50

---

apiVersion: v1
kind: Secret
metadata:
  name: collector-x-api-key
type: Opaque
stringData:
  password: "${COLLECTOR_X_API_KEY}"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector
spec:
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      containers:
      - name: collector
        image: "${ECR_BASE}/collector:${COLLECTOR_IMAGE_TAG}"
        env:
          - name: ENV
            value: production
          - name: PORT
            value: "${COLLECTOR_PORT}"
          - name: X_API_KEY
            valueFrom:
              secretKeyRef:
                name: collector-x-api-key
                key: password
          - name: LOG_LEVEL
            value: INFO
          - name: RMQ_TLS
            value: "${RMQ_TLS}"
          - name: RMQ_HOSTNAME
            value: "${RMQ_HOSTNAME}"
          - name: RMQ_USER
            value: "${RMQ_USER}"
          - name: RMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rmq-password
                key: password
          - name: RMQ_VHOST
            value: "${RMQ_VHOST}"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: ${COLLECTOR_PORT}
        livenessProbe:
          httpGet:
            path: /health
            port: ${COLLECTOR_PORT}
          initialDelaySeconds: 5
          periodSeconds: 10
